version: "3"
services:
# Create zookeeper service on Port: 2181
  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
  # Create Kafka service on Port: 9092
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - 9092:9092
    environment:
    # Local host address
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.26
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # Create kafka Manager on Port: 9000
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kakfa-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
